source 'https://rubygems.org'
ruby '2.0.0'

gem 'pg'

gem 'sinatra'

gem 'activerecord', '~>4.1'
gem 'activesupport', '~>4.1'

gem 'rake'

gem 'shotgun'


gem 'shoulda-matchers'
gem 'rack-test'
gem 'rspec'


gem 'factory_girl'

